using MainService.Models.Entities;

namespace MainService.Models.Helpers
{
    public class SeedDataSpecialties
    {
        public static readonly IEnumerable<Specialty> specialties =
        [
            new Specialty { Name = "Acupuntor", SpecialitySubSpecialties = [ new () {
                SubSpecialty = new () { Name = "Rehabilitación Integral" }
            } ] },
            new Specialty { Name = "Acupuntor", SpecialitySubSpecialties = [
                new () { SubSpecialty = new () { Name = "Rehabilitación Integral" } },
                new () { SubSpecialty = new () { Name = "Cáncer ginecólógico" } },
                new () { SubSpecialty = new () { Name = "Biomagnetismo" } },
            ] },
            new Specialty { Name = "Alergólogo" },
            new Specialty { Name = "Anatomopatólogo" },
            new Specialty { Name = "Anestesiólogo" },
            new Specialty { Name = "Angiólogo" },
            new Specialty { Name = "Audiólogo" },
            new Specialty { Name = "Cardiólogo" },
            new Specialty { Name = "Cardiólogo pediátrico" },
            new Specialty { Name = "Cirujano cardiovascular y torácico" },
            new Specialty { Name = "Cirujano de la mano" },
            new Specialty { Name = "Cirujano estético y cosmético" },
            new Specialty { Name = "Cirujano general" },
            new Specialty { Name = "Cirujano maxilofacial" },
            new Specialty { Name = "Cirujano oncólogo" },
            new Specialty { Name = "Cirujano pediátrico" },
            new Specialty { Name = "Cirujano plástico" },
            new Specialty { Name = "Dermatólogo" },
            new Specialty { Name = "Dermatólogo pediátrico" },
            new Specialty { Name = "Diabetólogo" },
            new Specialty { Name = "Endocrinólogo" },
            new Specialty { Name = "Endocrinólogo pediátrico" },
            new Specialty { Name = "Endoscopista" },
            new Specialty { Name = "Enfermero" },
            new Specialty { Name = "Fisioterapeuta" },
            new Specialty { Name = "Gastroenterólogo" },
            new Specialty { Name = "Gastroenterólogo pediátrico" },
            new Specialty { Name = "Genetista" },
            new Specialty { Name = "Geriatra" },
            new Specialty { Name = "Ginecólogo oncológico" },
            new Specialty { Name = "Ginecólogo" },
            new Specialty { Name = "Hematólogo" },
            new Specialty { Name = "Hematólogo pediatra" },
            new Specialty { Name = "Homeópata" },
            new Specialty { Name = "Infectólogo" },
            new Specialty { Name = "Infectólogo pediatra" },
            new Specialty { Name = "Inmunólogo" },
            new Specialty { Name = "Analista clínico" },
            new Specialty { Name = "Logopeda" },
            new Specialty { Name = "Terapeuta complementario" },
            new Specialty { Name = "Especialista en Medicina Crítica y Terapia Intensiva" },
            new Specialty { Name = "Especialista en Medicina del Deporte" },
            new Specialty { Name = "Especialista en Medicina del Trabajo" },
            new Specialty { Name = "Médico estético" },
            new Specialty { Name = "Médico de familia" },
            new Specialty { Name = "Médico general" },
            new Specialty { Name = "Especialista en Medicina Integrada" },
            new Specialty { Name = "Internista" },
            new Specialty { Name = "Especialista en Medicina Nuclear" },
            new Specialty { Name = "Especialista en Medicina Preventiva" },
            new Specialty { Name = "Naturista" },
            new Specialty { Name = "Nefrólogo" },
            new Specialty { Name = "Nefrólogo pediatra" },
            new Specialty { Name = "Neonatólogo" },
            new Specialty { Name = "Neumólogo" },
            new Specialty { Name = "Neumólogo pediatra" },
            new Specialty { Name = "Neurocirujano" },
            new Specialty { Name = "Neurofisiólogo" },
            new Specialty { Name = "Neurólogo" },
            new Specialty { Name = "Neurólogo pediatra" },
            new Specialty { Name = "Nutricionista" },
            new Specialty { Name = "Nutriólogo clínico" },
            new Specialty { Name = "Especialista en Obesidad y Delgadez" },
            new Specialty { Name = "Dentista - Odontólogo" },
            new Specialty { Name = "Oftalmólogo" },
            new Specialty { Name = "Oftalmólogo pediátrico" },
            new Specialty { Name = "Oncólogo médico" },
            new Specialty { Name = "Oncólogo pediátrico" },
            new Specialty { Name = "Optometrista" },
            new Specialty { Name = "Ortopedista" },
            new Specialty { Name = "Ortopedista infantil" },
            new Specialty { Name = "Otorrinolaringólogo" },
            new Specialty { Name = "Patólogo clínico" },
            new Specialty { Name = "Pediatra" },
            new Specialty { Name = "Podiatra" },
            new Specialty { Name = "Podólogo" },
            new Specialty { Name = "Proctólogo" },
            new Specialty { Name = "Psicoanalista" },
            new Specialty { Name = "Psicólogo" },
            new Specialty { Name = "Psicopedagogo" },
            new Specialty { Name = "Psiquiatra" },
            new Specialty { Name = "Psiquiatra infantil" },
            new Specialty { Name = "Quiropráctico" },
            new Specialty { Name = "Radiólogo" },
            new Specialty { Name = "Radioterapeuta" },
            new Specialty { Name = "Especialista en Rehabilitación y Medicina Física" },
            new Specialty { Name = "Especialista en Retina Médica y Quirúrgica" },
            new Specialty { Name = "Reumatólogo" },
            new Specialty { Name = "Sexólogo" },
            new Specialty { Name = "Algólogo" },
            new Specialty { Name = "Terapeuta ocupacional" },
            new Specialty { Name = "Traumatólogo" },
            new Specialty { Name = "Urgenciólogo" },
            new Specialty { Name = "Urólogo" },
            new Specialty { Name = "Reumatólogo pediátrico" },
            new Specialty { Name = "Cirujano cardiovascular y torácico pediátrico" },
            new Specialty { Name = "Urólogo pediátrico" },
            new Specialty { Name = "Cirujano cardiovascular" },
            new Specialty { Name = "Cirujano torácico" },
            new Specialty { Name = "Radio Oncólogo" },
            new Specialty { Name = "Epidemiólogo" },
            new Specialty { Name = "Odontólogo pediatra" },
            new Specialty { Name = "Cirujano bariatra" },
            new Specialty { Name = "Foniatra" },
            new Specialty { Name = "Otorrinolaringólogo Pediátrico" },
            new Specialty { Name = "Sin Especialidad" },
            new Specialty { Name = "Cirujano vascular" },
            new Specialty { Name = "Especialidad en Medicina del Enfermo Pediátrico en Estado Crítico" },
            new Specialty { Name = "Patólogo Bucal" },
            new Specialty { Name = "Gerontologo" },
            new Specialty { Name = "Técnico en diagnóstico e imagen" },
        ];
    }
}