// <auto-generated />
using System;
using MainService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainService.Postgres.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240624163909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MainService.Models.Entities.AppPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("MainService.Models.Entities.AppRolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("AppRolePermission");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("EmailVerificationCodeHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EmailVerificationCodeSalt")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("EmailVerificationExpiryTime")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastActive")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumberCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<byte[]>("PhoneNumberVerificationCodeHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PhoneNumberVerificationCodeSalt")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("PhoneNumberVerificationExpiryTime")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("MainService.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppointmentPrescription", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId", "PrescriptionId");

                    b.HasIndex("PrescriptionId")
                        .IsUnique();

                    b.ToTable("AppointmentPrescription");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorAppointment", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "AppointmentId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("DoctorAppointment");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorClinic", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "ClinicId");

                    b.HasIndex("ClinicId")
                        .IsUnique();

                    b.ToTable("DoctorClinic");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorInformation", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("InformationId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "InformationId");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.HasIndex("InformationId")
                        .IsUnique();

                    b.ToTable("DoctorInformation");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorLink", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("LinkId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "LinkId");

                    b.HasIndex("LinkId")
                        .IsUnique();

                    b.ToTable("DoctorLink");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorPhone", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "PhoneId");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("DoctorPhone");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorSignature", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("SignatureId")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "SignatureId");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.HasIndex("SignatureId")
                        .IsUnique();

                    b.ToTable("DoctorSignature");
                });

            modelBuilder.Entity("MainService.Models.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SiteName")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("MainService.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExteriorNumber")
                        .HasColumnType("text");

                    b.Property<string>("InteriorNumber")
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("MainService.Models.Entities.LocationPhone", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneId")
                        .HasColumnType("integer");

                    b.HasKey("LocationId", "PhoneId");

                    b.HasIndex("PhoneId")
                        .IsUnique();

                    b.ToTable("LocationPhone");
                });

            modelBuilder.Entity("MainService.Models.Entities.MedicalLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("SpecialtyLicense")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalLicense");
                });

            modelBuilder.Entity("MainService.Models.Entities.MedicalProfessionalLicense", b =>
                {
                    b.Property<int>("SpecialistSpecificationId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalLicenseId")
                        .HasColumnType("integer");

                    b.HasKey("SpecialistSpecificationId", "MedicalLicenseId");

                    b.HasIndex("MedicalLicenseId")
                        .IsUnique();

                    b.ToTable("MedicalProfessionalLicense");
                });

            modelBuilder.Entity("MainService.Models.Entities.NurseClinic", b =>
                {
                    b.Property<int>("NurseId")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.HasKey("NurseId", "ClinicId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("NurseId")
                        .IsUnique();

                    b.ToTable("NurseClinic");
                });

            modelBuilder.Entity("MainService.Models.Entities.PatientAppointment", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.HasKey("PatientId", "AppointmentId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("PatientAppointment");
                });

            modelBuilder.Entity("MainService.Models.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("MainService.Models.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MainService.Models.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorAddress")
                        .HasColumnType("text");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientAge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PatientDateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientFullName")
                        .HasColumnType("text");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("MainService.Models.Entities.PrescriptionLogo", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.HasKey("PrescriptionId", "PhotoId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("PrescriptionId")
                        .IsUnique();

                    b.ToTable("PrescriptionLogo");
                });

            modelBuilder.Entity("MainService.Models.Entities.PrescriptionMedicine", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosage")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("PrescriptionId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("PrescriptionMedicine");
                });

            modelBuilder.Entity("MainService.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MainService.Models.Entities.ProductPhoto", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "PhotoId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("ProductPhoto");
                });

            modelBuilder.Entity("MainService.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("MainService.Models.Entities.ServicePhoto", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.HasKey("ServiceId", "PhotoId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("ServicePhoto");
                });

            modelBuilder.Entity("MainService.Models.Entities.SpecialistSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SpecialistSpecification");
                });

            modelBuilder.Entity("MainService.Models.Entities.UserPhoto", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PhotoId");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MainService.Models.Entities.AppRolePermission", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUserPermission", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppPermission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUserRole", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.Models.Entities.Appointment", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("MainService.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppointmentPrescription", b =>
                {
                    b.HasOne("MainService.Models.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentPrescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Prescription", "Prescription")
                        .WithOne("AppointmentPrescription")
                        .HasForeignKey("MainService.Models.Entities.AppointmentPrescription", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorAppointment", b =>
                {
                    b.HasOne("MainService.Models.Entities.Appointment", "Appointment")
                        .WithOne("DoctorAppointment")
                        .HasForeignKey("MainService.Models.Entities.DoctorAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithMany("DoctorAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorClinic", b =>
                {
                    b.HasOne("MainService.Models.Entities.Location", "Clinic")
                        .WithOne("DoctorClinic")
                        .HasForeignKey("MainService.Models.Entities.DoctorClinic", "ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithMany("DoctorClinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorInformation", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithOne("DoctorInformation")
                        .HasForeignKey("MainService.Models.Entities.DoctorInformation", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.SpecialistSpecification", "Information")
                        .WithOne("DoctorInformation")
                        .HasForeignKey("MainService.Models.Entities.DoctorInformation", "InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Information");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorLink", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithMany("DoctorLinks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Link", "Link")
                        .WithOne("DoctorLink")
                        .HasForeignKey("MainService.Models.Entities.DoctorLink", "LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorPhone", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithMany("DoctorPhones")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Phone", "Phone")
                        .WithOne("DoctorPhone")
                        .HasForeignKey("MainService.Models.Entities.DoctorPhone", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("MainService.Models.Entities.DoctorSignature", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithOne("DoctorSignature")
                        .HasForeignKey("MainService.Models.Entities.DoctorSignature", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Photo", "Signature")
                        .WithOne("DoctorSignature")
                        .HasForeignKey("MainService.Models.Entities.DoctorSignature", "SignatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("MainService.Models.Entities.LocationPhone", b =>
                {
                    b.HasOne("MainService.Models.Entities.Location", "Location")
                        .WithMany("LocationPhones")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Phone", "Phone")
                        .WithOne("LocationPhone")
                        .HasForeignKey("MainService.Models.Entities.LocationPhone", "PhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("MainService.Models.Entities.MedicalProfessionalLicense", b =>
                {
                    b.HasOne("MainService.Models.Entities.MedicalLicense", "MedicalLicense")
                        .WithOne("MedicalProfessionalLicense")
                        .HasForeignKey("MainService.Models.Entities.MedicalProfessionalLicense", "MedicalLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.SpecialistSpecification", "SpecialistSpecification")
                        .WithMany("MedicalProfessionalLicenses")
                        .HasForeignKey("SpecialistSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalLicense");

                    b.Navigation("SpecialistSpecification");
                });

            modelBuilder.Entity("MainService.Models.Entities.NurseClinic", b =>
                {
                    b.HasOne("MainService.Models.Entities.Location", "Clinic")
                        .WithMany("NurseClinics")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "Nurse")
                        .WithOne("NurseClinic")
                        .HasForeignKey("MainService.Models.Entities.NurseClinic", "NurseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Nurse");
                });

            modelBuilder.Entity("MainService.Models.Entities.PatientAppointment", b =>
                {
                    b.HasOne("MainService.Models.Entities.Appointment", "Appointment")
                        .WithOne("PatientAppointment")
                        .HasForeignKey("MainService.Models.Entities.PatientAppointment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "Patient")
                        .WithMany("PatientAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MainService.Models.Entities.Prescription", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("MainService.Models.Entities.AppUser", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MainService.Models.Entities.PrescriptionLogo", b =>
                {
                    b.HasOne("MainService.Models.Entities.Photo", "Photo")
                        .WithOne("PrescriptionLogo")
                        .HasForeignKey("MainService.Models.Entities.PrescriptionLogo", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Prescription", "Prescription")
                        .WithOne("PrescriptionLogo")
                        .HasForeignKey("MainService.Models.Entities.PrescriptionLogo", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MainService.Models.Entities.PrescriptionMedicine", b =>
                {
                    b.HasOne("MainService.Models.Entities.Product", "Medicine")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MainService.Models.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("MainService.Models.Entities.ProductPhoto", b =>
                {
                    b.HasOne("MainService.Models.Entities.Photo", "Photo")
                        .WithOne("ProductPhoto")
                        .HasForeignKey("MainService.Models.Entities.ProductPhoto", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Product", "Product")
                        .WithMany("ProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MainService.Models.Entities.ServicePhoto", b =>
                {
                    b.HasOne("MainService.Models.Entities.Photo", "Photo")
                        .WithOne("ServicePhoto")
                        .HasForeignKey("MainService.Models.Entities.ServicePhoto", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.Service", "Service")
                        .WithMany("ServicePhotos")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MainService.Models.Entities.UserPhoto", b =>
                {
                    b.HasOne("MainService.Models.Entities.Photo", "Photo")
                        .WithOne("UserPhoto")
                        .HasForeignKey("MainService.Models.Entities.UserPhoto", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.Models.Entities.AppUser", "User")
                        .WithOne("UserPhoto")
                        .HasForeignKey("MainService.Models.Entities.UserPhoto", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MainService.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MainService.Models.Entities.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MainService.Models.Entities.AppUser", b =>
                {
                    b.Navigation("DoctorAppointments");

                    b.Navigation("DoctorClinics");

                    b.Navigation("DoctorInformation");

                    b.Navigation("DoctorLinks");

                    b.Navigation("DoctorPhones");

                    b.Navigation("DoctorSignature");

                    b.Navigation("NurseClinic");

                    b.Navigation("PatientAppointments");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserPhoto");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MainService.Models.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentPrescriptions");

                    b.Navigation("DoctorAppointment");

                    b.Navigation("PatientAppointment");
                });

            modelBuilder.Entity("MainService.Models.Entities.Link", b =>
                {
                    b.Navigation("DoctorLink");
                });

            modelBuilder.Entity("MainService.Models.Entities.Location", b =>
                {
                    b.Navigation("DoctorClinic");

                    b.Navigation("LocationPhones");

                    b.Navigation("NurseClinics");
                });

            modelBuilder.Entity("MainService.Models.Entities.MedicalLicense", b =>
                {
                    b.Navigation("MedicalProfessionalLicense");
                });

            modelBuilder.Entity("MainService.Models.Entities.Phone", b =>
                {
                    b.Navigation("DoctorPhone");

                    b.Navigation("LocationPhone");
                });

            modelBuilder.Entity("MainService.Models.Entities.Photo", b =>
                {
                    b.Navigation("DoctorSignature");

                    b.Navigation("PrescriptionLogo");

                    b.Navigation("ProductPhoto");

                    b.Navigation("ServicePhoto");

                    b.Navigation("UserPhoto");
                });

            modelBuilder.Entity("MainService.Models.Entities.Prescription", b =>
                {
                    b.Navigation("AppointmentPrescription");

                    b.Navigation("PrescriptionLogo");

                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("MainService.Models.Entities.Product", b =>
                {
                    b.Navigation("PrescriptionMedicines");

                    b.Navigation("ProductPhotos");
                });

            modelBuilder.Entity("MainService.Models.Entities.Service", b =>
                {
                    b.Navigation("ServicePhotos");
                });

            modelBuilder.Entity("MainService.Models.Entities.SpecialistSpecification", b =>
                {
                    b.Navigation("DoctorInformation");

                    b.Navigation("MedicalProfessionalLicenses");
                });
#pragma warning restore 612, 618
        }
    }
}
