export enum NotificationType {
  GENERAL = "general",
  APPOINTMENT_REMINDER = "appointment-reminder",
  APPOINTMENT_SCHEDULED = "appointment-scheduled",
  PRESCRIPTION_UPDATE = "prescription-update",
  BILLING_ALERT = "billing-alert",
  SYSTEM_ALERT = "system-alert",
  FEEDBACK_REQUEST = "feedback-request",
  SECURITY = "security",
  APPOINTMENT_CANCELLED = "appointment-cancelled",
  NURSE_ASSOCIATED = "nurse-associated",
  NURSE_INVITATION_SENT = "nurse-invitation-sent",
  NURSE_INVITATION_ACCEPTED = "nurse-invitation-accepted",
  NURSE_DISSOCIATED = "nurse-dissociated",
}
